name: Final Project CI Pipeline
on: [push]

# For non-pre built yahtzee containers, this needs to be done first.
  run: |
    apt update
    apt install -y make
    make setup-dependencies

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # ****** BUILD ***************************************************************
  # This workflow contains jobs to build this project
  build:
    name: "Build Source"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Build the software
        run: make build
      - name: Save JAR file
        uses: actions/upload-artifact@v3
        with:
          name: yahtzee jar
          path: target/*.jar

  # ***** TEST **************************************************************
  test:
    name: "Test Project"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Test the software
        run: make test

  # ***** Spellcheck **************************************************************
  spellcheck:
    name: "Spellcheck"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Spellcheck the software
        run: make spellcheck

  # ***** Javadoc **************************************************************
  javadoc:
    name: "Javadoc Generator"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Generate javadoc
        run: make javadoc
      - name: Archive Documentation
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs/
