name: Final Project CI Pipeline
on: [push]
jobs:
  setup:
    name: "Setup Area"
    runs-on: [self-hosted, linux, CPSC334]
    steps:
      - name: "Setting up dependencies"
        run: |
          apt update
          apt install -y make
          make setup-dependencies
  build:
    name: "Build Source"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Build the software
        run: make build
      - name: Save JAR file
        uses: actions/upload-artifact@v3
        with:
          name: yahtzee jar
          path: target/*.jar

  test:
    name: "Test Project"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Test the software
        run: make test
  spellcheck:
    name: "Spellcheck"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Spellcheck the software
        run: make spellcheck

  # ***** Javadoc **************************************************************
  javadoc:
    name: "Javadoc Generator"
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Generate javadoc
        run: make javadoc
      - name: Archive Documentation
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs/
